import type { WordPair } from "./types";

export const WORD_PAIRS: WordPair[] = [
  // ── Easy ────────────────────────────────────────────────────────────────────
  { civil: "Chien", undercover: "Chat", difficulty: "easy" },
  { civil: "Pizza", undercover: "Burger", difficulty: "easy" },
  { civil: "Été", undercover: "Hiver", difficulty: "easy" },
  { civil: "Mer", undercover: "Montagne", difficulty: "easy" },
  { civil: "Vélo", undercover: "Moto", difficulty: "easy" },
  { civil: "Soleil", undercover: "Lune", difficulty: "easy" },
  { civil: "Train", undercover: "Avion", difficulty: "easy" },
  { civil: "Café", undercover: "Thé", difficulty: "easy" },
  { civil: "Football", undercover: "Rugby", difficulty: "easy" },
  { civil: "Guitare", undercover: "Piano", difficulty: "easy" },
  { civil: "Pomme", undercover: "Poire", difficulty: "easy" },
  { civil: "Bière", undercover: "Vin", difficulty: "easy" },
  { civil: "Cinéma", undercover: "Théâtre", difficulty: "easy" },
  { civil: "Chat", undercover: "Lapin", difficulty: "easy" },
  { civil: "Natation", undercover: "Course à pied", difficulty: "easy" },
  { civil: "Paris", undercover: "Londres", difficulty: "easy" },
  { civil: "Chocolat", undercover: "Caramel", difficulty: "easy" },
  { civil: "Livre", undercover: "Magazine", difficulty: "easy" },
  { civil: "Médecin", undercover: "Infirmier", difficulty: "easy" },
  { civil: "Table", undercover: "Bureau", difficulty: "easy" },
  { civil: "Maison", undercover: "Appartement", difficulty: "easy" },
  { civil: "Jardin", undercover: "Parc", difficulty: "easy" },
  { civil: "Rose", undercover: "Tulipe", difficulty: "easy" },
  { civil: "Orange", undercover: "Citron", difficulty: "easy" },
  { civil: "Fraise", undercover: "Framboise", difficulty: "easy" },
  { civil: "Pain", undercover: "Brioche", difficulty: "easy" },
  { civil: "Lait", undercover: "Jus d'orange", difficulty: "easy" },
  { civil: "Coca", undercover: "Pepsi", difficulty: "easy" },
  { civil: "Jour", undercover: "Nuit", difficulty: "easy" },
  { civil: "Printemps", undercover: "Automne", difficulty: "easy" },
  { civil: "Chaud", undercover: "Froid", difficulty: "easy" },
  { civil: "Petit", undercover: "Grand", difficulty: "easy" },
  { civil: "Noir", undercover: "Blanc", difficulty: "easy" },
  { civil: "École", undercover: "Université", difficulty: "easy" },
  { civil: "Frère", undercover: "Sœur", difficulty: "easy" },
  { civil: "Fête", undercover: "Anniversaire", difficulty: "easy" },
  { civil: "Cadeau", undercover: "Surprise", difficulty: "easy" },
  { civil: "Glace", undercover: "Sorbet", difficulty: "easy" },
  { civil: "Gâteau", undercover: "Tarte", difficulty: "easy" },
  { civil: "T-shirt", undercover: "Pull", difficulty: "easy" },
  { civil: "Manteau", undercover: "Veste", difficulty: "easy" },
  { civil: "Jupe", undercover: "Robe", difficulty: "easy" },
  { civil: "Pantalon", undercover: "Jean", difficulty: "easy" },
  { civil: "Chapeau", undercover: "Casquette", difficulty: "easy" },
  { civil: "Voiture", undercover: "Camion", difficulty: "easy" },
  { civil: "Bus", undercover: "Tramway", difficulty: "easy" },
  { civil: "Bateau", undercover: "Barque", difficulty: "easy" },
  { civil: "Tennis", undercover: "Badminton", difficulty: "easy" },
  { civil: "Ski", undercover: "Snowboard", difficulty: "easy" },
  { civil: "Cheval", undercover: "Âne", difficulty: "easy" },
  { civil: "Vache", undercover: "Mouton", difficulty: "easy" },
  { civil: "Poulet", undercover: "Canard", difficulty: "easy" },
  { civil: "Lion", undercover: "Tigre", difficulty: "easy" },
  { civil: "Éléphant", undercover: "Rhinocéros", difficulty: "easy" },
  { civil: "Girafe", undercover: "Zèbre", difficulty: "easy" },
  { civil: "Singe", undercover: "Gorille", difficulty: "easy" },
  { civil: "Hibou", undercover: "Aigle", difficulty: "easy" },
  { civil: "Film", undercover: "Série", difficulty: "easy" },
  { civil: "Roman", undercover: "Bande dessinée", difficulty: "easy" },
  { civil: "Dessin", undercover: "Peinture", difficulty: "easy" },
  { civil: "Téléphone", undercover: "Tablette", difficulty: "easy" },
  { civil: "Supermarché", undercover: "Épicerie", difficulty: "easy" },
  { civil: "Boulangerie", undercover: "Pâtisserie", difficulty: "easy" },
  { civil: "Hôtel", undercover: "Auberge", difficulty: "easy" },
  { civil: "Aéroport", undercover: "Gare", difficulty: "easy" },
  { civil: "Musée", undercover: "Galerie", difficulty: "easy" },
  { civil: "Bibliothèque", undercover: "Librairie", difficulty: "easy" },
  { civil: "Plage", undercover: "Piscine", difficulty: "easy" },
  { civil: "Mariage", undercover: "Fiançailles", difficulty: "easy" },
  { civil: "Montre", undercover: "Bracelet", difficulty: "easy" },
  { civil: "Chaussures", undercover: "Sandales", difficulty: "easy" },
  { civil: "Banane", undercover: "Mangue", difficulty: "easy" },
  { civil: "Raisin", undercover: "Cerise", difficulty: "easy" },
  { civil: "Carotte", undercover: "Navet", difficulty: "easy" },
  { civil: "Soupe", undercover: "Bouillon", difficulty: "easy" },
  { civil: "Forêt", undercover: "Jungle", difficulty: "easy" },
  { civil: "Rivière", undercover: "Fleuve", difficulty: "easy" },
  { civil: "Nuage", undercover: "Brouillard", difficulty: "easy" },
  { civil: "Orage", undercover: "Tempête", difficulty: "easy" },
  { civil: "Neige", undercover: "Grêle", difficulty: "easy" },
  { civil: "Bonbon", undercover: "Sucette", difficulty: "easy" },
  { civil: "Jeu vidéo", undercover: "Jeu de société", difficulty: "easy" },
  { civil: "Flûte", undercover: "Trompette", difficulty: "easy" },
  { civil: "Lunettes", undercover: "Loupe", difficulty: "easy" },
  { civil: "Basket", undercover: "Handball", difficulty: "easy" },
  { civil: "Île", undercover: "Presqu'île", difficulty: "easy" },
  { civil: "Perroquet", undercover: "Perruche", difficulty: "easy" },
  { civil: "Salade", undercover: "Épinards", difficulty: "easy" },
  { civil: "Moto", undercover: "Scooter", difficulty: "easy" },
  { civil: "Lac", undercover: "Étang", difficulty: "easy" },
  { civil: "Volcan", undercover: "Geyser", difficulty: "easy" },
  { civil: "Arc-en-ciel", undercover: "Aurore boréale", difficulty: "easy" },
  { civil: "Fusée", undercover: "Satellite", difficulty: "easy" },
  { civil: "Professeur", undercover: "Instituteur", difficulty: "easy" },
  { civil: "Policier", undercover: "Gendarme", difficulty: "easy" },
  { civil: "Pompier", undercover: "Sauveteur", difficulty: "easy" },
  { civil: "Bague", undercover: "Alliance", difficulty: "easy" },
  { civil: "Collier", undercover: "Pendentif", difficulty: "easy" },
  { civil: "Puzzle", undercover: "Memory", difficulty: "easy" },
  { civil: "Chaussette", undercover: "Collant", difficulty: "easy" },
  { civil: "Bougie", undercover: "Lampe", difficulty: "easy" },
  { civil: "Fromage", undercover: "Yaourt", difficulty: "easy" },
  { civil: "Riz", undercover: "Pâtes", difficulty: "easy" },
  { civil: "Sel", undercover: "Poivre", difficulty: "easy" },
  { civil: "Beurre", undercover: "Margarine", difficulty: "easy" },
  { civil: "Confiture", undercover: "Miel", difficulty: "easy" },
  { civil: "Trottinette", undercover: "Rollers", difficulty: "easy" },
  { civil: "Piscine", undercover: "Lac", difficulty: "easy" },
  { civil: "Sapin", undercover: "Palmier", difficulty: "easy" },
  { civil: "Fleur", undercover: "Plante", difficulty: "easy" },
  { civil: "Oiseau", undercover: "Poisson", difficulty: "easy" },
  { civil: "Souris", undercover: "Rat", difficulty: "easy" },
  { civil: "Hamster", undercover: "Cochon d'Inde", difficulty: "easy" },
  { civil: "Tortue", undercover: "Escargot", difficulty: "easy" },
  { civil: "Abeille", undercover: "Guêpe", difficulty: "easy" },
  { civil: "Papillon", undercover: "Libellule", difficulty: "easy" },
  { civil: "Araignée", undercover: "Scorpion", difficulty: "easy" },
  { civil: "Serpent", undercover: "Lézard", difficulty: "easy" },
  { civil: "Grenouille", undercover: "Crapaud", difficulty: "easy" },
  { civil: "Sac", undercover: "Valise", difficulty: "easy" },
  { civil: "Parapluie", undercover: "Imperméable", difficulty: "easy" },
  { civil: "Miroir", undercover: "Vitre", difficulty: "easy" },
  { civil: "Porte", undercover: "Fenêtre", difficulty: "easy" },
  { civil: "Escalier", undercover: "Ascenseur", difficulty: "easy" },
  { civil: "Balcon", undercover: "Terrasse", difficulty: "easy" },
  { civil: "Cheminée", undercover: "Radiateur", difficulty: "easy" },
  { civil: "Oreiller", undercover: "Coussin", difficulty: "easy" },
  { civil: "Couverture", undercover: "Drap", difficulty: "easy" },
  { civil: "Brosse à dents", undercover: "Dentifrice", difficulty: "easy" },
  { civil: "Savon", undercover: "Shampoing", difficulty: "easy" },
  { civil: "Serviette", undercover: "Peignoir", difficulty: "easy" },
  { civil: "Crayon", undercover: "Stylo", difficulty: "easy" },
  { civil: "Cahier", undercover: "Classeur", difficulty: "easy" },
  { civil: "Gomme", undercover: "Taille-crayon", difficulty: "easy" },
  { civil: "Trousse", undercover: "Sac à dos", difficulty: "easy" },
  { civil: "Tableau", undercover: "Affiche", difficulty: "easy" },
  { civil: "Horloge", undercover: "Réveil", difficulty: "easy" },
  { civil: "Radio", undercover: "Télévision", difficulty: "easy" },
  { civil: "Ordinateur", undercover: "Console", difficulty: "easy" },
  { civil: "Clavier", undercover: "Souris d'ordinateur", difficulty: "easy" },
  { civil: "Casque", undercover: "Écouteurs", difficulty: "easy" },
  { civil: "Batterie", undercover: "Chargeur", difficulty: "easy" },
  { civil: "Camping-car", undercover: "Caravane", difficulty: "easy" },
  { civil: "Tente", undercover: "Cabane", difficulty: "easy" },
  { civil: "Feu de camp", undercover: "Barbecue", difficulty: "easy" },
  { civil: "Randonnée", undercover: "Promenade", difficulty: "easy" },
  { civil: "Marché", undercover: "Supermarché", difficulty: "easy" },
  { civil: "Boucherie", undercover: "Poissonnerie", difficulty: "easy" },
  { civil: "Pharmacie", undercover: "Parapharmacie", difficulty: "easy" },
  { civil: "Banque", undercover: "Bureau de poste", difficulty: "easy" },
  { civil: "Mairie", undercover: "Préfecture", difficulty: "easy" },
  { civil: "Église", undercover: "Cathédrale", difficulty: "easy" },
  { civil: "Château", undercover: "Palais", difficulty: "easy" },
  { civil: "Pont", undercover: "Tunnel", difficulty: "easy" },
  { civil: "Route", undercover: "Autoroute", difficulty: "easy" },
  { civil: "Feu rouge", undercover: "Passage piéton", difficulty: "easy" },
  { civil: "Vélo électrique", undercover: "Trottinette électrique", difficulty: "easy" },
  { civil: "Camping", undercover: "Colonie de vacances", difficulty: "easy" },
  { civil: "Anniversaire", undercover: "Noël", difficulty: "easy" },
  { civil: "Pâques", undercover: "Halloween", difficulty: "easy" },
  { civil: "Ballon", undercover: "Frisbee", difficulty: "easy" },
  { civil: "Corde à sauter", undercover: "Élastique", difficulty: "easy" },
  { civil: "Toboggan", undercover: "Balançoire", difficulty: "easy" },
  { civil: "Poupée", undercover: "Peluche", difficulty: "easy" },
  { civil: "Robot", undercover: "Drone", difficulty: "easy" },
  { civil: "Château de sable", undercover: "Bonhomme de neige", difficulty: "easy" },
  { civil: "Sirène", undercover: "Fée", difficulty: "easy" },
  { civil: "Dragon", undercover: "Dinosaure", difficulty: "easy" },
  { civil: "Pirate", undercover: "Chevalier", difficulty: "easy" },
  { civil: "Astronaute", undercover: "Cosmonaute", difficulty: "easy" },
  { civil: "Clown", undercover: "Magicien", difficulty: "easy" },

  // ── Medium ───────────────────────────────────────────────────────────────────
  { civil: "Violon", undercover: "Alto", difficulty: "medium" },
  { civil: "Netflix", undercover: "Disney+", difficulty: "medium" },
  { civil: "Sushi", undercover: "Maki", difficulty: "medium" },
  { civil: "Boxe", undercover: "MMA", difficulty: "medium" },
  { civil: "Yoga", undercover: "Pilates", difficulty: "medium" },
  { civil: "Vodka", undercover: "Tequila", difficulty: "medium" },
  { civil: "Instagram", undercover: "TikTok", difficulty: "medium" },
  { civil: "Baguette", undercover: "Croissant", difficulty: "medium" },
  { civil: "Loup", undercover: "Renard", difficulty: "medium" },
  { civil: "Requin", undercover: "Dauphin", difficulty: "medium" },
  { civil: "Avocat", undercover: "Notaire", difficulty: "medium" },
  { civil: "Psychologue", undercover: "Psychiatre", difficulty: "medium" },
  { civil: "Escalade", undercover: "Alpinisme", difficulty: "medium" },
  { civil: "Ramen", undercover: "Pho", difficulty: "medium" },
  { civil: "Platine vinyle", undercover: "Chaîne hi-fi", difficulty: "medium" },
  { civil: "Camembert", undercover: "Brie", difficulty: "medium" },
  { civil: "Jacuzzi", undercover: "Sauna", difficulty: "medium" },
  { civil: "Tatouage", undercover: "Piercing", difficulty: "medium" },
  { civil: "Architecte", undercover: "Designer", difficulty: "medium" },
  { civil: "Marathon", undercover: "Triathlon", difficulty: "medium" },
  { civil: "Poker", undercover: "Blackjack", difficulty: "medium" },
  { civil: "Rugby", undercover: "Football américain", difficulty: "medium" },
  { civil: "Saumon", undercover: "Thon", difficulty: "medium" },
  { civil: "Whisky", undercover: "Rhum", difficulty: "medium" },
  { civil: "Gin", undercover: "Bourbon", difficulty: "medium" },
  { civil: "Vélo de route", undercover: "VTT", difficulty: "medium" },
  { civil: "Judo", undercover: "Karaté", difficulty: "medium" },
  { civil: "Volley-ball", undercover: "Handball", difficulty: "medium" },
  { civil: "Skate", undercover: "Trottinette", difficulty: "medium" },
  { civil: "Patinage", undercover: "Luge", difficulty: "medium" },
  { civil: "Kayak", undercover: "Rafting", difficulty: "medium" },
  { civil: "Parachutisme", undercover: "Deltaplane", difficulty: "medium" },
  { civil: "Husky", undercover: "Malamute", difficulty: "medium" },
  { civil: "Berger allemand", undercover: "Labrador", difficulty: "medium" },
  { civil: "Panthère", undercover: "Jaguar", difficulty: "medium" },
  { civil: "Flamant rose", undercover: "Pélican", difficulty: "medium" },
  { civil: "Baleine", undercover: "Orque", difficulty: "medium" },
  { civil: "Pieuvre", undercover: "Calmar", difficulty: "medium" },
  { civil: "Jazz", undercover: "Blues", difficulty: "medium" },
  { civil: "Hip-hop", undercover: "Rap", difficulty: "medium" },
  { civil: "Pop", undercover: "R&B", difficulty: "medium" },
  { civil: "Techno", undercover: "House", difficulty: "medium" },
  { civil: "Comédie", undercover: "Drame", difficulty: "medium" },
  { civil: "Thriller", undercover: "Policier", difficulty: "medium" },
  { civil: "Fantasy", undercover: "Science-fiction", difficulty: "medium" },
  { civil: "Spotify", undercover: "Deezer", difficulty: "medium" },
  { civil: "Uber", undercover: "Bolt", difficulty: "medium" },
  { civil: "Airbnb", undercover: "Booking", difficulty: "medium" },
  { civil: "Nike", undercover: "Adidas", difficulty: "medium" },
  { civil: "PlayStation", undercover: "Xbox", difficulty: "medium" },
  { civil: "Minecraft", undercover: "Roblox", difficulty: "medium" },
  { civil: "Linguini", undercover: "Tagliatelles", difficulty: "medium" },
  { civil: "Risotto", undercover: "Paella", difficulty: "medium" },
  { civil: "Kebab", undercover: "Tacos", difficulty: "medium" },
  { civil: "Crêpe", undercover: "Gaufre", difficulty: "medium" },
  { civil: "Tiramisu", undercover: "Panna cotta", difficulty: "medium" },
  { civil: "Macaron", undercover: "Financier", difficulty: "medium" },
  { civil: "Journaliste", undercover: "Reporter", difficulty: "medium" },
  { civil: "Photographe", undercover: "Vidéaste", difficulty: "medium" },
  { civil: "Scénariste", undercover: "Réalisateur", difficulty: "medium" },
  { civil: "Acteur", undercover: "Comédien", difficulty: "medium" },
  { civil: "DJ", undercover: "Producteur", difficulty: "medium" },
  { civil: "Crossfit", undercover: "Musculation", difficulty: "medium" },
  { civil: "Escrime", undercover: "Tir à l'arc", difficulty: "medium" },
  { civil: "Pétanque", undercover: "Bowling", difficulty: "medium" },
  { civil: "Bordeaux", undercover: "Bourgogne", difficulty: "medium" },
  { civil: "Kombucha", undercover: "Kéfir", difficulty: "medium" },
  { civil: "Siamois", undercover: "Persan", difficulty: "medium" },
  { civil: "Phoque", undercover: "Otarie", difficulty: "medium" },
  { civil: "Comics", undercover: "Roman graphique", difficulty: "medium" },
  { civil: "Kinésithérapeute", undercover: "Ostéopathe", difficulty: "medium" },
  { civil: "Dermatologue", undercover: "Chirurgien esthétique", difficulty: "medium" },
  { civil: "Vegan", undercover: "Végétarien", difficulty: "medium" },
  { civil: "Spinning", undercover: "Zumba", difficulty: "medium" },
  { civil: "Aigle", undercover: "Faucon", difficulty: "medium" },
  { civil: "Mangue", undercover: "Papaye", difficulty: "medium" },
  { civil: "Guacamole", undercover: "Tzatziki", difficulty: "medium" },
  { civil: "Mojito", undercover: "Caïpirinha", difficulty: "medium" },
  { civil: "Champagne", undercover: "Crémant", difficulty: "medium" },
  { civil: "Boulimie", undercover: "Anorexie", difficulty: "medium" },
  { civil: "Surf", undercover: "Wakeboard", difficulty: "medium" },
  { civil: "Snowboard", undercover: "Ski de fond", difficulty: "medium" },
  { civil: "Apple", undercover: "Samsung", difficulty: "medium" },
  { civil: "Freelance", undercover: "Consultant", difficulty: "medium" },
  { civil: "Podcast", undercover: "Audiobook", difficulty: "medium" },
  { civil: "Startup", undercover: "Scale-up", difficulty: "medium" },
  { civil: "Influenceur", undercover: "Créateur de contenu", difficulty: "medium" },
  { civil: "Streaming", undercover: "Téléchargement", difficulty: "medium" },
  { civil: "Réalité virtuelle", undercover: "Réalité augmentée", difficulty: "medium" },
  { civil: "Impression 3D", undercover: "Découpe laser", difficulty: "medium" },
  { civil: "Coliving", undercover: "Coworking", difficulty: "medium" },
  { civil: "Miso", undercover: "Tahini", difficulty: "medium" },
  { civil: "Bibimbap", undercover: "Pad thaï", difficulty: "medium" },
  { civil: "Tarot", undercover: "Astrologie", difficulty: "medium" },
  { civil: "Méditation", undercover: "Pleine conscience", difficulty: "medium" },
  { civil: "Randonnée", undercover: "Trekking", difficulty: "medium" },
  { civil: "Camping", undercover: "Glamping", difficulty: "medium" },
  { civil: "Fermentation", undercover: "Lacto-fermentation", difficulty: "medium" },
  { civil: "Jardinière", undercover: "Serre", difficulty: "medium" },
  { civil: "Karting", undercover: "Quad", difficulty: "medium" },
  { civil: "Bourbon", undercover: "Scotch", difficulty: "medium" },
  { civil: "Rhum", undercover: "Cachaça", difficulty: "medium" },
  { civil: "Sancerre", undercover: "Chablis", difficulty: "medium" },
  { civil: "IPA", undercover: "Stout", difficulty: "medium" },
  { civil: "Espresso", undercover: "Cappuccino", difficulty: "medium" },
  { civil: "Latte", undercover: "Macchiato", difficulty: "medium" },
  { civil: "Matcha", undercover: "Chaï", difficulty: "medium" },
  { civil: "Smoothie", undercover: "Milkshake", difficulty: "medium" },
  { civil: "Falafel", undercover: "Houmous", difficulty: "medium" },
  { civil: "Curry", undercover: "Tikka masala", difficulty: "medium" },
  { civil: "Naan", undercover: "Chapati", difficulty: "medium" },
  { civil: "Dim sum", undercover: "Nems", difficulty: "medium" },
  { civil: "Poke bowl", undercover: "Buddha bowl", difficulty: "medium" },
  { civil: "Burrito", undercover: "Quesadilla", difficulty: "medium" },
  { civil: "Ceviche", undercover: "Tartare", difficulty: "medium" },
  { civil: "Fondue", undercover: "Raclette", difficulty: "medium" },
  { civil: "Cassoulet", undercover: "Choucroute", difficulty: "medium" },
  { civil: "Bouillabaisse", undercover: "Paella", difficulty: "medium" },
  { civil: "Escargots", undercover: "Cuisses de grenouille", difficulty: "medium" },
  { civil: "Foie gras", undercover: "Rillettes", difficulty: "medium" },
  { civil: "Roquefort", undercover: "Bleu d'Auvergne", difficulty: "medium" },
  { civil: "Comté", undercover: "Beaufort", difficulty: "medium" },
  { civil: "Mozzarella", undercover: "Burrata", difficulty: "medium" },
  { civil: "Parmesan", undercover: "Pecorino", difficulty: "medium" },
  { civil: "Prosciutto", undercover: "Bresaola", difficulty: "medium" },
  { civil: "Chorizo", undercover: "Saucisson", difficulty: "medium" },
  { civil: "Boudin noir", undercover: "Andouillette", difficulty: "medium" },
  { civil: "Pilates", undercover: "Barre au sol", difficulty: "medium" },
  { civil: "Trail", undercover: "Ultra-trail", difficulty: "medium" },
  { civil: "Aviron", undercover: "Canoë", difficulty: "medium" },
  { civil: "Voile", undercover: "Planche à voile", difficulty: "medium" },
  { civil: "Plongée", undercover: "Snorkeling", difficulty: "medium" },
  { civil: "Kitesurf", undercover: "Windsurf", difficulty: "medium" },
  { civil: "Paddle", undercover: "Kayak de mer", difficulty: "medium" },
  { civil: "Rollerblade", undercover: "Skateboard", difficulty: "medium" },
  { civil: "BMX", undercover: "VTT descente", difficulty: "medium" },
  { civil: "Squash", undercover: "Padel", difficulty: "medium" },
  { civil: "Water-polo", undercover: "Natation synchronisée", difficulty: "medium" },
  { civil: "Gymnastique", undercover: "Trampoline", difficulty: "medium" },
  { civil: "Danse classique", undercover: "Danse contemporaine", difficulty: "medium" },
  { civil: "Salsa", undercover: "Bachata", difficulty: "medium" },
  { civil: "Tango", undercover: "Valse", difficulty: "medium" },
  { civil: "Breakdance", undercover: "Krump", difficulty: "medium" },
  { civil: "Rock", undercover: "Metal", difficulty: "medium" },
  { civil: "Reggae", undercover: "Ska", difficulty: "medium" },
  { civil: "Funk", undercover: "Disco", difficulty: "medium" },
  { civil: "Punk", undercover: "Grunge", difficulty: "medium" },
  { civil: "Opéra rock", undercover: "Comédie musicale", difficulty: "medium" },
  { civil: "Vinyle", undercover: "Cassette", difficulty: "medium" },
  { civil: "Twitch", undercover: "YouTube", difficulty: "medium" },
  { civil: "Snapchat", undercover: "BeReal", difficulty: "medium" },
  { civil: "Discord", undercover: "Slack", difficulty: "medium" },
  { civil: "WhatsApp", undercover: "Messenger", difficulty: "medium" },
  { civil: "LinkedIn", undercover: "Indeed", difficulty: "medium" },
  { civil: "Amazon", undercover: "Cdiscount", difficulty: "medium" },
  { civil: "Tesla", undercover: "Rivian", difficulty: "medium" },
  { civil: "Vélo cargo", undercover: "Vélo pliant", difficulty: "medium" },
  { civil: "Trottinette électrique", undercover: "Gyroroue", difficulty: "medium" },
  { civil: "Sommelier", undercover: "Œnologue", difficulty: "medium" },
  { civil: "Barista", undercover: "Torréfacteur", difficulty: "medium" },
  { civil: "Pâtissier", undercover: "Boulanger", difficulty: "medium" },
  { civil: "Chef cuisinier", undercover: "Second de cuisine", difficulty: "medium" },
  { civil: "Traiteur", undercover: "Cuisinier à domicile", difficulty: "medium" },
  { civil: "Architecte d'intérieur", undercover: "Décorateur", difficulty: "medium" },
  { civil: "Illustrateur", undercover: "Graphiste", difficulty: "medium" },
  { civil: "Community manager", undercover: "Social media manager", difficulty: "medium" },
  { civil: "Data analyst", undercover: "Data scientist", difficulty: "medium" },
  { civil: "UX designer", undercover: "UI designer", difficulty: "medium" },
  { civil: "Bière blonde", undercover: "Bière ambrée", difficulty: "medium" },
  { civil: "Cidre", undercover: "Poiré", difficulty: "medium" },
  { civil: "Feta", undercover: "Halloumi", difficulty: "medium" },
  { civil: "Houblon", undercover: "Malt", difficulty: "medium" },

  // ── Hard ─────────────────────────────────────────────────────────────────────
  { civil: "Oxygène", undercover: "Azote", difficulty: "hard" },
  { civil: "FBI", undercover: "CIA", difficulty: "hard" },
  { civil: "Champagne", undercover: "Prosecco", difficulty: "hard" },
  { civil: "Golf", undercover: "Polo", difficulty: "hard" },
  { civil: "Cubisme", undercover: "Impressionnisme", difficulty: "hard" },
  { civil: "Procrastiner", undercover: "Flemmarder", difficulty: "hard" },
  { civil: "Andante", undercover: "Allegro", difficulty: "hard" },
  { civil: "Sonar", undercover: "Radar", difficulty: "hard" },
  { civil: "Épée", undercover: "Fleuret", difficulty: "hard" },
  { civil: "Botox", undercover: "Acide hyaluronique", difficulty: "hard" },
  { civil: "Scalpel", undercover: "Bistouri", difficulty: "hard" },
  { civil: "Grenadine", undercover: "Sirop de menthe", difficulty: "hard" },
  { civil: "Compost", undercover: "Fumier", difficulty: "hard" },
  { civil: "Notaire", undercover: "Huissier", difficulty: "hard" },
  { civil: "Mise en scène", undercover: "Chorégraphie", difficulty: "hard" },
  { civil: "VPN", undercover: "Proxy", difficulty: "hard" },
  { civil: "Sprint", undercover: "Itération", difficulty: "hard" },
  { civil: "Hedge fund", undercover: "Private equity", difficulty: "hard" },
  { civil: "Synapse", undercover: "Dendrite", difficulty: "hard" },
  { civil: "Mélatonine", undercover: "Sérotonine", difficulty: "hard" },
  { civil: "Collagène", undercover: "Élastine", difficulty: "hard" },
  { civil: "Mitose", undercover: "Méiose", difficulty: "hard" },
  { civil: "Phagocyte", undercover: "Lymphocyte", difficulty: "hard" },
  { civil: "Endorphine", undercover: "Dopamine", difficulty: "hard" },
  { civil: "PIB", undercover: "PNB", difficulty: "hard" },
  { civil: "Récession", undercover: "Stagflation", difficulty: "hard" },
  { civil: "Oligopole", undercover: "Duopole", difficulty: "hard" },
  { civil: "Dividende", undercover: "Coupon obligataire", difficulty: "hard" },
  { civil: "Inflation", undercover: "Déflation", difficulty: "hard" },
  { civil: "Stoïcisme", undercover: "Épicurisme", difficulty: "hard" },
  { civil: "Phénoménologie", undercover: "Herméneutique", difficulty: "hard" },
  { civil: "Syllogisme", undercover: "Enthymème", difficulty: "hard" },
  { civil: "Métaphore", undercover: "Métonymie", difficulty: "hard" },
  { civil: "Allitération", undercover: "Assonance", difficulty: "hard" },
  { civil: "Surréalisme", undercover: "Dadaïsme", difficulty: "hard" },
  { civil: "Art déco", undercover: "Art nouveau", difficulty: "hard" },
  { civil: "Baroque", undercover: "Rococo", difficulty: "hard" },
  { civil: "Aquarelle", undercover: "Gouache", difficulty: "hard" },
  { civil: "Sérigraphie", undercover: "Lithographie", difficulty: "hard" },
  { civil: "Sonnet", undercover: "Haïku", difficulty: "hard" },
  { civil: "Bémol", undercover: "Dièse", difficulty: "hard" },
  { civil: "Pizzicato", undercover: "Vibrato", difficulty: "hard" },
  { civil: "Arpège", undercover: "Accord", difficulty: "hard" },
  { civil: "Soprano", undercover: "Mezzo-soprano", difficulty: "hard" },
  { civil: "Baryton", undercover: "Ténor", difficulty: "hard" },
  { civil: "Symphonie", undercover: "Concerto", difficulty: "hard" },
  { civil: "Séquoia", undercover: "Baobab", difficulty: "hard" },
  { civil: "Permafrost", undercover: "Toundra", difficulty: "hard" },
  { civil: "Stalactite", undercover: "Stalagmite", difficulty: "hard" },
  { civil: "Basalte", undercover: "Granite", difficulty: "hard" },
  { civil: "Saphir", undercover: "Rubis", difficulty: "hard" },
  { civil: "Émeraude", undercover: "Jade", difficulty: "hard" },
  { civil: "Météorite", undercover: "Astéroïde", difficulty: "hard" },
  { civil: "Quasar", undercover: "Pulsar", difficulty: "hard" },
  { civil: "Antimatière", undercover: "Matière noire", difficulty: "hard" },
  { civil: "Neutrino", undercover: "Boson", difficulty: "hard" },
  { civil: "Biais cognitif", undercover: "Heuristique", difficulty: "hard" },
  { civil: "Dissonance cognitive", undercover: "Rationalisation", difficulty: "hard" },
  { civil: "Transfert", undercover: "Contre-transfert", difficulty: "hard" },
  { civil: "Archétype", undercover: "Persona", difficulty: "hard" },
  { civil: "Paradigme", undercover: "Épistémè", difficulty: "hard" },
  { civil: "Empirisme", undercover: "Rationalisme", difficulty: "hard" },
  { civil: "Utilitarisme", undercover: "Déontologie", difficulty: "hard" },
  { civil: "Fédéralisme", undercover: "Confédéralisme", difficulty: "hard" },
  { civil: "Laïcité", undercover: "Sécularisme", difficulty: "hard" },
  { civil: "Populisme", undercover: "Démagogie", difficulty: "hard" },
  { civil: "Soft power", undercover: "Hard power", difficulty: "hard" },
  { civil: "Isotope", undercover: "Isomère", difficulty: "hard" },
  { civil: "Plasmide", undercover: "Chromosome", difficulty: "hard" },
  { civil: "Contrepoint", undercover: "Fugue", difficulty: "hard" },
  { civil: "Alexandrin", undercover: "Décasyllabe", difficulty: "hard" },
  { civil: "Oxymore", undercover: "Paradoxe", difficulty: "hard" },
  { civil: "Pointillisme", undercover: "Divisionnisme", difficulty: "hard" },
  { civil: "Fresque", undercover: "Mosaïque", difficulty: "hard" },
  { civil: "Warrant", undercover: "Option", difficulty: "hard" },
  { civil: "Futures", undercover: "Swap", difficulty: "hard" },
  { civil: "Cortex", undercover: "Hypothalamus", difficulty: "hard" },
  { civil: "Keynésianisme", undercover: "Monétarisme", difficulty: "hard" },
  { civil: "Dialectique", undercover: "Sophisme", difficulty: "hard" },
  { civil: "Géopolitique", undercover: "Géostratégie", difficulty: "hard" },
  { civil: "Démocratie directe", undercover: "Démocratie représentative", difficulty: "hard" },
  { civil: "Nominalisme", undercover: "Réalisme philosophique", difficulty: "hard" },
  { civil: "Gravure", undercover: "Estampe", difficulty: "hard" },
  { civil: "Opéra", undercover: "Opérette", difficulty: "hard" },
  { civil: "Mangrove", undercover: "Tourbière", difficulty: "hard" },
  { civil: "Schiste", undercover: "Ardoise", difficulty: "hard" },
  { civil: "Opale", undercover: "Améthyste", difficulty: "hard" },
  { civil: "Trou noir", undercover: "Nébuleuse", difficulty: "hard" },
  { civil: "Mécanisme de défense", undercover: "Refoulement", difficulty: "hard" },
  { civil: "Myopie", undercover: "Astigmatisme", difficulty: "hard" },
  { civil: "Infarctus", undercover: "AVC", difficulty: "hard" },
  { civil: "Appendicite", undercover: "Péritonite", difficulty: "hard" },
  { civil: "Anesthésie générale", undercover: "Anesthésie locale", difficulty: "hard" },
  { civil: "Chimiothérapie", undercover: "Radiothérapie", difficulty: "hard" },
  { civil: "IRM", undercover: "Scanner", difficulty: "hard" },
  { civil: "Hémoglobine", undercover: "Globule blanc", difficulty: "hard" },
  { civil: "Pandémie", undercover: "Épidémie", difficulty: "hard" },
  { civil: "Vaccin ARNm", undercover: "Vaccin à vecteur viral", difficulty: "hard" },
  { civil: "Protocole TCP", undercover: "Protocole UDP", difficulty: "hard" },
  { civil: "Chiffrement symétrique", undercover: "Chiffrement asymétrique", difficulty: "hard" },
  { civil: "Machine learning", undercover: "Deep learning", difficulty: "hard" },
  { civil: "Algorithme", undercover: "Heuristique", difficulty: "hard" },
  { civil: "Blockchain", undercover: "Distributed ledger", difficulty: "hard" },
  { civil: "Épistémologie", undercover: "Ontologie", difficulty: "hard" },
  { civil: "Solipsisme", undercover: "Idéalisme", difficulty: "hard" },
  { civil: "Nietzschéen", undercover: "Hégélien", difficulty: "hard" },
  { civil: "Structuralisme", undercover: "Post-structuralisme", difficulty: "hard" },
  { civil: "Existentialisme", undercover: "Absurdisme", difficulty: "hard" },
  { civil: "Anarchisme", undercover: "Libertarianisme", difficulty: "hard" },
  { civil: "Théocratie", undercover: "Ploutocratie", difficulty: "hard" },
  { civil: "Bicamérisme", undercover: "Monocamérisme", difficulty: "hard" },
  { civil: "Referendum", undercover: "Plébiscite", difficulty: "hard" },
  { civil: "Kelvin", undercover: "Celsius", difficulty: "hard" },
  { civil: "Fission", undercover: "Fusion nucléaire", difficulty: "hard" },
  { civil: "Photon", undercover: "Électron", difficulty: "hard" },
  { civil: "Supraconducteur", undercover: "Semi-conducteur", difficulty: "hard" },
  { civil: "Entropie", undercover: "Enthalpie", difficulty: "hard" },
  { civil: "Covalent", undercover: "Ionique", difficulty: "hard" },
  { civil: "Catalyseur", undercover: "Inhibiteur", difficulty: "hard" },
  { civil: "Polymère", undercover: "Monomère", difficulty: "hard" },
  { civil: "Allèle", undercover: "Locus", difficulty: "hard" },
  { civil: "Phénotype", undercover: "Génotype", difficulty: "hard" },
  { civil: "Mutation", undercover: "Recombinaison génétique", difficulty: "hard" },
  { civil: "Osmose", undercover: "Diffusion", difficulty: "hard" },
  { civil: "Photosynthèse", undercover: "Respiration cellulaire", difficulty: "hard" },
  { civil: "Neurone miroir", undercover: "Neurone sensoriel", difficulty: "hard" },
  { civil: "Amygdale cérébrale", undercover: "Hippocampe", difficulty: "hard" },
  { civil: "Anxiolytique", undercover: "Antidépresseur", difficulty: "hard" },
  { civil: "Placebo", undercover: "Nocebo", difficulty: "hard" },
  { civil: "Étude randomisée", undercover: "Étude observationnelle", difficulty: "hard" },
  { civil: "Prévalence", undercover: "Incidence", difficulty: "hard" },
  { civil: "Immunité innée", undercover: "Immunité acquise", difficulty: "hard" },
  { civil: "Autoimmunité", undercover: "Allergie", difficulty: "hard" },
  { civil: "Cirrhose", undercover: "Hépatite", difficulty: "hard" },
  { civil: "Arythmie", undercover: "Tachycardie", difficulty: "hard" },
  { civil: "Prothèse", undercover: "Orthèse", difficulty: "hard" },
  { civil: "Litote", undercover: "Euphémisme", difficulty: "hard" },
  { civil: "Antiphrase", undercover: "Ironie dramatique", difficulty: "hard" },
  { civil: "Anaphore", undercover: "Épiphore", difficulty: "hard" },
  { civil: "Chiasme", undercover: "Antithèse", difficulty: "hard" },
  { civil: "Pentamètre iambique", undercover: "Hexamètre", difficulty: "hard" },
  { civil: "Villanelle", undercover: "Pantoum", difficulty: "hard" },
  { civil: "Réalisme magique", undercover: "Fantastique littéraire", difficulty: "hard" },
  { civil: "Roman épistolaire", undercover: "Journal intime fictif", difficulty: "hard" },
  { civil: "Rétable", undercover: "Triptyque", difficulty: "hard" },
  { civil: "Clair-obscur", undercover: "Sfumato", difficulty: "hard" },
  { civil: "Fauvisme", undercover: "Expressionnisme", difficulty: "hard" },
  { civil: "Op art", undercover: "Art cinétique", difficulty: "hard" },
  { civil: "Land art", undercover: "Art conceptuel", difficulty: "hard" },
  { civil: "Contreplaqué", undercover: "MDF", difficulty: "hard" },
  { civil: "Titane", undercover: "Tungstène", difficulty: "hard" },
  { civil: "Alliage", undercover: "Composite", difficulty: "hard" },
  { civil: "Fibre de carbone", undercover: "Fibre de verre", difficulty: "hard" },
  { civil: "Amortisseur", undercover: "Suspension pneumatique", difficulty: "hard" },
  { civil: "Turbocompresseur", undercover: "Compresseur volumétrique", difficulty: "hard" },
  { civil: "Boîte manuelle", undercover: "Boîte automatique", difficulty: "hard" },
  { civil: "Hybride rechargeable", undercover: "Véhicule électrique", difficulty: "hard" },
  { civil: "Cache mémoire", undercover: "Mémoire vive", difficulty: "hard" },
  { civil: "Latence réseau", undercover: "Bande passante", difficulty: "hard" },
  { civil: "Chiffrement", undercover: "Hachage", difficulty: "hard" },
  { civil: "API REST", undercover: "GraphQL", difficulty: "hard" },
  { civil: "Conteneurisation", undercover: "Virtualisation", difficulty: "hard" },
  { civil: "Réseau de neurones", undercover: "Arbre de décision", difficulty: "hard" },
  { civil: "Overfitting", undercover: "Underfitting", difficulty: "hard" },
  { civil: "Taux d'intérêt réel", undercover: "Taux d'intérêt nominal", difficulty: "hard" },
  { civil: "Actif liquide", undercover: "Actif illiquide", difficulty: "hard" },
  { civil: "Obligation souveraine", undercover: "Obligation corporate", difficulty: "hard" },
  { civil: "Effet de levier", undercover: "Effet de massue", difficulty: "hard" },
  { civil: "Amortissement linéaire", undercover: "Amortissement dégressif", difficulty: "hard" },
  { civil: "Monopole naturel", undercover: "Monopole légal", difficulty: "hard" },
  { civil: "Externalité positive", undercover: "Externalité négative", difficulty: "hard" },
  { civil: "Bien public", undercover: "Bien commun", difficulty: "hard" },
];

const USED_PAIRS_KEY = "undercover-used-pairs";
const USED_PAIRS_TTL_MS = 24 * 60 * 60 * 1000;

function pairKey(pair: WordPair): string {
  return `${pair.civil}|||${pair.undercover}`;
}

function loadUsedPairKeys(): { key: string; usedAt: number }[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(USED_PAIRS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as { key: string; usedAt: number }[];
    const now = Date.now();
    return parsed.filter((r) => now - r.usedAt < USED_PAIRS_TTL_MS);
  } catch {
    return [];
  }
}

function saveUsedPairKeys(records: { key: string; usedAt: number }[]): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(USED_PAIRS_KEY, JSON.stringify(records));
}

export function getRandomPair(difficulty: "easy" | "medium" | "hard"): WordPair {
  const pool = WORD_PAIRS.filter((p) => p.difficulty === difficulty);
  const used = loadUsedPairKeys();
  const usedKeys = new Set(used.map((u) => u.key));

  let available = pool.filter((p) => !usedKeys.has(pairKey(p)));
  let nextUsed = used;

  // Every pair in this difficulty was already used this session — free them up again
  if (available.length === 0) {
    const poolKeys = new Set(pool.map(pairKey));
    nextUsed = used.filter((u) => !poolKeys.has(u.key));
    available = pool;
  }

  const pair = available[Math.floor(Math.random() * available.length)] ?? pool[0]!;
  saveUsedPairKeys([...nextUsed, { key: pairKey(pair), usedAt: Date.now() }]);
  return pair;
}
